apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: commonhall

resources:
  - namespace.yaml
  - secrets.yaml
  - postgres.yaml
  - redis.yaml
  - elasticsearch.yaml
  - api.yaml
  - web.yaml
  - ingress.yaml
